language: node_js
sudo: false
node_js:
  - 4
  - 6
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14

os:
  - linux
  - osx
compiler:
  - g++
  - clang++
script:
  - npm test

notifications:
  email: false
