environment:
  matrix:
    - nodejs_version: '14'
    - nodejs_version: '13'
    - nodejs_version: '12'
    - nodejs_version: '11'
    - nodejs_version: '10'
    - nodejs_version: '9'
    - nodejs_version: '8'
    - nodejs_version: '6'
    - nodejs_version: '4'

version: '{build}'

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  - set PATH=%APPDATA%\npm;%PATH%
  - node --version
  - npm --version
  - npm install

matrix:
  fast_finish: false

# No need for MSBuild on this project
build: off

test_script:
  - npm test
